nbpApiUrl: 'http://api.nbp.pl/api/exchangerates/tables/A?format=json'
ratesForOfflineModeFileName: response.json 
nbpApiKnownCurrencies: 
  - GBP
  - EUR
  - PLN
countries:
-
    countryCode: UK
    currencyCode: GBP
    fixedCostAmount: 600
    taxRate: 0.25
-
    countryCode: DE
    currencyCode: EUR
    fixedCostAmount: 800
    taxRate: 0.20
-
    countryCode: PL
    currencyCode: PLN
    fixedCostAmount: 1200
    taxRate: 0.19
